aws_region: "us-east-1"

services:
  ecs:
    cluster_name: "my-ecs-cluster"
    instance_type: "t3.medium"
  s3:
    bucket_name: "my-app-bucket"
  iam:
    roles:
      - name: "AppAdminRole"
        policies:
          - "arn:aws:iam::aws:policy/AdministratorAccess"
      - name: "ReadOnlyRole"
        policies:
          - "arn:aws:iam::aws:policy/ReadOnlyAccess"
    groups:
      - name: "AdminGroup"
        policies:
          - "arn:aws:iam::aws:policy/AdministratorAccess"
      - name: "ReadOnlyGroup"
        policies:
          - "arn:aws:iam::aws:policy/ReadOnlyAccess"
